// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RESTful.Database;

#nullable disable

namespace RESTful.Migrations
{
  [DbContext(typeof(WebAppDBContext))]
  [Migration("20240524002906_init")]
  partial class init
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "8.0.5")
        .HasAnnotation("Relational:MaxIdentifierLength", 64);

      MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

      modelBuilder.Entity("RESTful.Models.WeatherForecast", b =>
      {
        b.Property<int>("Id")
          .ValueGeneratedOnAdd()
          .HasColumnType("int");

        MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

        b.Property<DateOnly>("Date")
          .HasColumnType("date");

        b.Property<string>("Summary")
          .HasColumnType("longtext");

        b.Property<int>("TemperatureC")
          .HasColumnType("int");

        b.HasKey("Id");

        b.ToTable("WeatherForecasts");
      });
#pragma warning restore 612, 618
    }
  }
}
